#!/bin/bash

# =============================================================================
# generate_secrets.sh
# Generates Configurations/Secrets.xcconfig from an envs/.env.<ENV_NAME> file.
# The output file is git-ignored — never commit it.
#
# Usage:
#   ENV_NAME=development ./scripts/generate_secrets.sh
#   ENV_NAME=staging     ./scripts/generate_secrets.sh
#   ENV_NAME=production  ./scripts/generate_secrets.sh
#
# Each scheme runs this as a build pre-action for its own environment, so switching
# schemes never builds against a stale environment. Pre-action output is invisible in
# Xcode's build log, so the schemes redirect it to /tmp/ccam_secrets.log — that file is
# the first thing to check when a build behaves as if a setting never resolved.
# =============================================================================

set -euo pipefail

# =========================================
# CONSTANTS
# =========================================

VALID_ENVIRONMENTS=("development" "staging" "production")
SCRIPTS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPTS_DIR")"
OUTPUT_DIR="${PROJECT_ROOT}/Configurations"
OUTPUT_FILE="${OUTPUT_DIR}/Secrets.xcconfig"

# =========================================
# VALIDATION
# =========================================

if [[ -z "${ENV_NAME:-}" ]]; then
    echo "Error: ENV_NAME is not set."
    echo ""
    echo "Usage:"
    echo "  ENV_NAME=development ./scripts/generate_secrets.sh"
    echo "  ENV_NAME=staging     ./scripts/generate_secrets.sh"
    echo "  ENV_NAME=production  ./scripts/generate_secrets.sh"
    exit 1
fi

ENV_NAME=$(echo "$ENV_NAME" | tr '[:upper:]' '[:lower:]')

VALID=false
for env in "${VALID_ENVIRONMENTS[@]}"; do
    [[ "$ENV_NAME" == "$env" ]] && VALID=true && break
done

if [[ "$VALID" == false ]]; then
    echo "Error: Invalid ENV_NAME '$ENV_NAME'. Valid values: ${VALID_ENVIRONMENTS[*]}"
    exit 1
fi

ENV_FILE="${PROJECT_ROOT}/envs/.env.${ENV_NAME}"

# A missing .env is not an error here. Configurations/App.xcconfig includes Secrets.xcconfig
# with `#include?`, so a fresh clone builds and runs on the simulator without one; only device
# signing needs CCAM_TEAM_ID. Warn and exit clean rather than failing the build pre-action.
if [[ ! -f "$ENV_FILE" ]]; then
    echo "warning: no $ENV_FILE — skipping Secrets.xcconfig generation."
    echo "  Simulator builds work without it. To sign for a device:"
    echo "    cp envs/.env.example envs/.env.${ENV_NAME}"
    echo "    Then set CCAM_TEAM_ID to your Apple Developer Team ID."
    exit 0
fi

if [[ ! -d "$OUTPUT_DIR" ]]; then
    echo "Error: Output directory not found: $OUTPUT_DIR"
    exit 1
fi

# =========================================
# UP-TO-DATE CHECK
# =========================================

# Skip regeneration when the source .env is older than the existing Secrets.xcconfig AND the
# previous run was for the same environment. The env name is recorded in the header below, so
# a scheme switch (e.g. development -> staging) still forces a regeneration.
if [[ -f "$OUTPUT_FILE" && "$ENV_FILE" -ot "$OUTPUT_FILE" ]]; then
    PREVIOUS_ENV=$(grep -m1 '^// Environment:' "$OUTPUT_FILE" | awk '{print $3}' || true)
    if [[ "$PREVIOUS_ENV" == "$ENV_NAME" ]]; then
        echo "Secrets.xcconfig is up-to-date for $ENV_NAME; skipping."
        exit 0
    fi
fi

# =========================================
# ENCODING
# =========================================

# Encodes a value so it is safe to use in an xcconfig file.
# xcconfig special characters that must be escaped:
#
#   \    escape character       ->  \\
#   $(   variable expansion     ->  $$(   (prevents Xcode interpreting a value as a build var)
#   //   comment delimiter      ->  :/$()/  (Xcode resolves $() as empty at build time)
#
encodeForXcconfig() {
    local value="$1"

    # 1. Backslashes first — must be encoded before any replacement that introduces backslashes
    value="${value//\\/\\\\}"

    # 2. $( -> $$( — prevent Xcode treating part of a value as a build setting expansion
    value="${value//\$\(/\$\$\(}"

    # 3. // -> /$()/ — prevent xcconfig treating // as a comment delimiter.
    #    Uses sed to avoid bash expanding $() during string replacement.
    value=$(printf '%s' "$value" | sed 's|//|/$()/|g')

    echo "$value"
}

# =========================================
# GENERATE
# =========================================

echo "Generating Secrets.xcconfig for environment: $ENV_NAME"
echo "  Source : $ENV_FILE"
echo "  Output : $OUTPUT_FILE"

printf "// Secrets.xcconfig\n" > "$OUTPUT_FILE"
printf "// Auto-generated by scripts/generate_secrets.sh\n" >> "$OUTPUT_FILE"
printf "// DO NOT EDIT MANUALLY — DO NOT COMMIT THIS FILE\n" >> "$OUTPUT_FILE"
printf "// Regenerate: ENV_NAME=%s ./scripts/generate_secrets.sh\n" "$ENV_NAME" >> "$OUTPUT_FILE"
printf "// Generated : %s\n" "$(date)" >> "$OUTPUT_FILE"
printf "// Environment: %s\n\n" "$ENV_NAME" >> "$OUTPUT_FILE"

# Parse .env and convert KEY=VALUE -> KEY = VALUE (xcconfig format).
# Skips blank lines and comments, strips surrounding quotes, encodes for xcconfig.
KEY_COUNT=0
while IFS= read -r line || [[ -n "$line" ]]; do
    [[ -z "$line" ]] && continue
    [[ "$line" =~ ^# ]] && continue
    [[ "$line" != *"="* ]] && continue

    KEY="${line%%=*}"
    VALUE="${line#*=}"

    VALUE="${VALUE%\"}" ; VALUE="${VALUE#\"}"
    VALUE="${VALUE%\'}" ; VALUE="${VALUE#\'}"

    KEY="$(echo "$KEY" | xargs)"
    VALUE="$(encodeForXcconfig "$VALUE")"

    echo "${KEY} = ${VALUE}" >> "$OUTPUT_FILE"
    KEY_COUNT=$((KEY_COUNT + 1))
done < "$ENV_FILE"

echo "Done: $KEY_COUNT keys written to $OUTPUT_FILE"
echo ""
echo "WARNING: Never commit Secrets.xcconfig or envs/.env.* to git."
